// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3eBM8SdAG03O6UZzjUUthsvmX1icyTx8',
    appId: '1:771116931125:web:88db18fa7140f3c30bf97c',
    messagingSenderId: '771116931125',
    projectId: 'shyeyes-55006',
    authDomain: 'shyeyes-55006.firebaseapp.com',
    storageBucket: 'shyeyes-55006.firebasestorage.app',
    measurementId: 'G-8DCN4K95SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5BglrJYPeYf5dXy--4JEI_lYx6KEe00M',
    appId: '1:771116931125:android:7f800deaf0682b300bf97c',
    messagingSenderId: '771116931125',
    projectId: 'shyeyes-55006',
    storageBucket: 'shyeyes-55006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTVIRPMpAOZzwST7JROg7BwGdqbFhS6jc',
    appId: '1:771116931125:ios:9d2ca1218a30b56f0bf97c',
    messagingSenderId: '771116931125',
    projectId: 'shyeyes-55006',
    storageBucket: 'shyeyes-55006.firebasestorage.app',
    iosBundleId: 'com.playzelo.shyeyes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTVIRPMpAOZzwST7JROg7BwGdqbFhS6jc',
    appId: '1:771116931125:ios:9d2ca1218a30b56f0bf97c',
    messagingSenderId: '771116931125',
    projectId: 'shyeyes-55006',
    storageBucket: 'shyeyes-55006.firebasestorage.app',
    iosBundleId: 'com.playzelo.shyeyes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3eBM8SdAG03O6UZzjUUthsvmX1icyTx8',
    appId: '1:771116931125:web:eec8e22596bcf91c0bf97c',
    messagingSenderId: '771116931125',
    projectId: 'shyeyes-55006',
    authDomain: 'shyeyes-55006.firebaseapp.com',
    storageBucket: 'shyeyes-55006.firebasestorage.app',
    measurementId: 'G-R8NDQGCDC0',
  );
}
